import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { lusitana } from "./ui/fonts";
import { cn } from "./lib/utility";
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Next Keep Focus",
    description: "Generated by create next app",
    icons: {
        icon: "https://fav.farm/clock"
    }
};

export default function RootLayout({
    children,
}: Readonly<{ children: React.ReactNode }>
) {
    return (
        <html
            lang="en"
            className={`${geistSans.variable} ${geistMono.variable} ${lusitana.className} h-full antialiased`}
        >
            <body className={cn(
                `min-h-full flex flex-col`
            )}>{children}</body>
        </html>
    );
}
